# Site settings
title: Ion
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A group of state government leaders responsible for fostering the use of state government data as a strategic asset.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://statecdonetwork.github.io" # the base hostname & protocol for your site
twitter_username: technickle
github_username:  StateCDONetwork

# Build settings
markdown: kramdown
